services:
  db:
    image: postgres:15
    container_name: postgres_tc
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tech_challenge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_tc
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tech_challenge
    command: npm run dev

volumes:
  pgdata:
